version: "3.8"
services:
  app:
    container_name: backend
    build: ./
    command: sh -c "sleep 5 && ./banner-service"
    ports:
      - "8888:8080"
    depends_on:
      - db
    environment:
      - CONFIG_PATH=./configs/docker.yaml
  db:
    container_name: psql
    restart: always
    image: "postgres:16.2"
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5436:5432"